import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Button from "../components/Button";
import Header from "../components/Header";
import MenuItem from "../components/MenuItem";

export type OrderSchema = {
  name: string;
  price: number;
  amount: number;
};

export type MenuSchema = {
  nama: string;
  description?: string;
  price: number;
  picture: string;
};

export const DaftarMenu: MenuSchema[] = [
  {
    nama: "Nasi Goreng",
    description: "Nasi goreng dengan telur, bawang, dan sambal",
    price: 10000,
    picture:
      "https://akcdn.detik.net.id/community/media/visual/2022/09/17/resep-nasi-goreng-udang-kemangi_43.jpeg?w=700&q=90",
  },
  {
    nama: "Ikan Bakar",
    description: "Ikan bakar dengan saus tomat dan bumbu khas",
    price: 27000,
    picture:
      "https://i0.wp.com/resepkoki.id/wp-content/uploads/2017/10/Resep-Ikan-bakar-bumbu-bali.jpg?fit=500%2C488&ssl=1",
  },
  {
    nama: "Sate Ayam",
    description: "Sate ayam dengan bumbu kacang",
    price: 15000,
    picture:
      "https://assets.resepedia.id/assets/images/2020/06/1669574651186208-sate-ayam.jpeg",
  },
  {
    nama: "Soto Lamongan",
    description: "Soto lamongan dengan kuah santan",
    price: 13000,
    picture:
      "https://assets.pikiran-rakyat.com/crop/0x508:821x1011/x/photo/2022/04/26/2747824482.jpg",
  },
  {
    nama: "Kari Ayam",
    description: "Kari ayam gurih",
    price: 15000,
    picture:
      "https://sweetrip.id/wp-content/uploads/2021/05/183153973_519627052542432_4787831301420097868_n.jpg",
  },
  {
    nama: "Es Teh",
    description: "Es teh manis",
    price: 3000,
    picture:
      "https://dcostseafood.id/wp-content/uploads/2021/12/Es-teh-tawar-manis.jpg",
  },
];

export const calculateTotal = (orders: OrderSchema[]) => {
  let total = 0;

  orders.forEach((order) => {
    total += order.price * order.amount;
  });

  return total;
};

export default function Home() {
  const [orders, setOrders] = useState<OrderSchema[]>([]);

  const updateOrder = (order: OrderSchema) => {
    const index = orders.findIndex((o) => o.name == order.name);

    if (index > -1) {
      orders[index] = order;
    } else {
      orders.push(order);
    }

    // Remove order if amount is 0
    if (order.amount == 0) {
      orders.splice(index, 1);
    }

    setOrders([...orders]);
  };

  return (
    <div>
      <Head>
        <title>Recandy | Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header tableNumber={5} />

      <main className="px-4 py-6">
        <section
          id="menu"
          className="z-0 flex flex-col space-y-6 overflow-y-auto max-h-102 "
        >
          {DaftarMenu.map((m) => (
            <MenuItem
              key={m.nama}
              nama={m.nama}
              description={m.description}
              price={m.price}
              picture={m.picture}
              updateOrder={updateOrder}
            />
          ))}
        </section>
      </main>

      {orders.length > 0 && (
        <section
          id="order-now"
          className="fixed z-10 w-full px-4 pt-2 bg-white bottom-20"
        >
          <Link href={"/"}>
            <Button variant="primary" className="text-sm">
              Pesan Rp. {calculateTotal(orders)}
            </Button>
          </Link>
        </section>
      )}

      <nav className="fixed bottom-0 grid w-full grid-cols-2 px-4 py-4 text-white bg-green-700">
        <Link href={"/minuman"}>
          <div id="beverage" className="flex flex-col items-center">
            <svg
              className="w-5 h-5 stroke-white"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M17.79 10.47V17.79C17.79 20.12 15.9 22 13.58 22H6.21C3.89 22 2 20.11 2 17.79V10.47C2 8.14001 3.89 6.26001 6.21 6.26001H13.58C15.9 6.26001 17.79 8.15001 17.79 10.47Z"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M5.5 4V2.25"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M9.5 4V2.25"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M13.5 4V2.25"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M22 13.16C22 15.48 20.11 17.37 17.79 17.37V8.94995C20.11 8.94995 22 10.83 22 13.16Z"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M2 12H17.51"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>

            <p className="text-xs">Minuman</p>
          </div>
        </Link>

        <Link href={"/makanan"}>
          <div id="food" className="flex flex-col items-center">
            <svg
              className="w-5 h-5 stroke-white"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M18.97 22H4.96997C1.96997 22 1.96997 20.65 1.96997 19V18C1.96997 17.45 2.41997 17 2.96997 17H20.97C21.52 17 21.97 17.45 21.97 18V19C21.97 20.65 21.97 22 18.97 22Z"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M20.72 13V17H3.27002V13C3.27002 9.16 5.98002 5.95 9.59002 5.18C10.13 5.06 10.69 5 11.27 5H12.72C13.3 5 13.87 5.06 14.41 5.18C18.02 5.96 20.72 9.16 20.72 13Z"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M14.5 4.5C14.5 4.74 14.47 4.96 14.41 5.18C13.87 5.06 13.3 5 12.72 5H11.27C10.69 5 10.13 5.06 9.59 5.18C9.53 4.96 9.5 4.74 9.5 4.5C9.5 3.12 10.62 2 12 2C13.38 2 14.5 3.12 14.5 4.5Z"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M15 11H9"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>

            <p className="text-xs">Makanan</p>
          </div>
        </Link>
      </nav>
    </div>
  );
}
